print("##############################")
print("#                            #")
print("#   Muhammad Hafiz Ansari    #")
print("#      2210817210003         #")
print("#                            #")
print("##############################")